### ISSUE TITLE
kubernetes系列(九) - 深入掌握Service

### ISSUE THREAD

**Issue by lzw5399** [lzw5399/blogs#12]
- [1. Service概念](#head1)
- [2. Service的类型](#head2)
	- [2.1 ClusterIP（默认）](#head3)
		- [2.1.1 原理](#head4)
		- [2.1.2 ClusterIP资源清单](#head5)
	- [2.2 NodePort](#head6)
		- [2.2.1 NodePort资源清单](#head7)
	- [2.3 LoadBalancer](#head8)
	- [2.4 ExternalName](#head9)
- [3.  Service代理模式](#head10)
	- [3.1 userspace](#head11)
	- [3.2 iptables](#head12)
		- [3.2.1 原理](#head13)
		- [3.2.2 查看iptables代理规则](#head14)
	- [3.3 ipvs](#head15)
		- [3.3.1 原理](#head16)
		- [3.3.2 查看ipvs代理规则](#head17)
- [4. Headless Service](#head18)
	- [4.1 存在的意义](#head19)
	- [4.2 Headless Service资源清单](#head20)

## <span id="head1">1. Service概念</span>

通过创建`service`可以为一组相同功能的容器应用提供一个统一的入口，并将请求均衡负载发送到后端的各个容器应用上

- 通常是通过`label selector`来实现选中具体哪些容器的
- 均衡负载算法默认是RR (`Round-Robin 轮询调度`) 
- 还可以通过设置`service.spec.sessionAffinity`=`ClientIp`来启用`SessionAffinity`策略
- `service`只提供4层负载均衡能力(`只能基于ip地址和端口进行转发`)，而没有7层功能(`不能通过主机名及域名的方案去进行负载均衡`)，但有时我们可能需要更多的匹配规则来转发请求，这点上4层负载均衡是不支持的

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggcyrwty5uj30m80bqtef.jpg)

### <span id="head3">2.1 ClusterIP（默认）</span>

在集群的内部ip上公开服务。这种类型使得只能从集群内访问服务

#### <span id="head4">2.1.1 原理</span>

clusterIP主要在每个node节点使用iptables(`新版本模式是ipvs`)，将发向`clusterlP`对应端口的数据，转发到`kube-proxy`中。然后`kube-proxy`自己内部实现有负载均衡的方法，并可以查询到这个service下对应pod的地址和端口，进而把数据转发给对应的pod的地址和端口

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gge4v5mkisj30mo0bs40j.jpg)

为了实现图上的功能，需要以下几个组件协调工作：
- `api-server`：用户通过`kubectl`命令向`apiserver`发送创建`service`的命令，`apiserver`接收到请求后将数据存储到`etcd`中
- `kube-proxy`: `kubernetes`的每个节点中都有一个叫做`kube-porxy`的进程，这个进程负责感知`service`，`pod`的变化，并将变化的信息写入本地的`iptables`规则中
- `iptables`:  使用`NAT`等技术将`virtuallP`的流量转至`endpoint`中

#### <span id="head5">2.1.2 ClusterIP资源清单</span>

```
apiVersion: v1 
kind: Service 
metadata:
  name: myapp 
  namespace: default 
spec:
  type: ClusterIP 
  selector:
    app: myapp 
    release: stabel 
  ports:
  - name: http 
    port: 80 
    targetPort: 80
```

### <span id="head6">2.2 NodePort</span>

在每个node上的相同端口上公开服务，可以从集群外部访问服务。`ClusterIP的超集`, 最常用

#### <span id="head7">2.2.1 NodePort资源清单</span>

```
apiVersion: v1 
kind: Service 
metadata:
  name: myapp 
  namespace: default 
spec:
  type: NodePort 
  selector:
    app: myapp 
    release: stabel 
  ports:
  - name: http 
    port: 80 
    targetPort: 80
```

- iptables查询nodeport
```
iptables -t nat -nvL KUBE-NODEPORTS
```

### <span id="head8">2.3 LoadBalancer</span>

在`NodePort`的基础上，在当前云中创建一个外部负载平衡器（如果支持），并为该服务分配一个固定的外部IP。`NodePort的超集`
> 即使用云服务商均衡负载服务，需要付费

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1gge539dgt4j30il0dujun.jpg)

### <span id="head9">2.4 ExternalName</span>

通过返回具有该名称的CNAME记录，使用任意名称（在规范中指定）公开服务。不使用代理。此类型需要v1.7或更高版本kube-dns

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  type: ExternalName
  externalName: hub.coreqi.cn
```

## <span id="head10">3.  Service代理模式</span>

在kubernetes集群中，为每个节点运行了一个`kube-proxy`，`kube-proxy`负责为`service`实现一种`virtual ip`的形式，而这个过程称之为`service代理模式`。**不同的kubernetes版本，代理模式的实现方式也不尽相同，前后共有三种模式**：

1. `userspace`：kubernetes v1.0版本使用的是这种代理模式，已过期
2. `iptables`：从kubernetes v1.2开始使用iptables
3. `ipvs`：kubernetes v1.14开始默认使用ipvs代理

### <span id="head11">3.1 userspace</span>

从下可以看出客户端想要访问到具体的`server pod`，需要
1. 经过防火墙iptables
2. 经过`kube-proxy`负责转发
3. 到达`server pod`

- 缺点：对`kube-proxy`的压力很大

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggd131y54ej30li0fjgt3.jpg)

#### <span id="head13">3.2.1 原理</span>

从下可以看出客户端想要访问到具体的`server pod`，需要
1. 经过`iptables`直接转发
2. 到达`server pod`

- 这过程中`kube-proxy`只负责维护`iptables`的对应规则

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggd15yr1rcj30lt0evwlu.jpg)

#### <span id="head14">3.2.2 查看iptables代理规则</span>

```
iptables -t nat -nvl
iptables -t nat -nvL KUBE-NODEPORTS
```

#### <span id="head16">3.3.1 原理</span>

从下可以看出客户端想要访问到具体的`server pod`，需要
1. 经过`ipvs`直接转发
2. 到达`server pod`

ipvs这种模式，`kube-proxy`会监视`Kubernetes service` 对象和`Endpoints`，调用`netlink` 接口以相应地创建`ipvs` 规则并定期与Kubernetes `service对象`和`Endpoints 对象`同步ipvs规则，以确保ipvs状态与期望一致。访问服务时，流量将被重定向到其中一个后端 Pod
与iptables类似，ipvs于`netfilter`的hook功能，但使用哈希表作为底层数据结构并在内核空间中工作。这意味着ipvs可以更快地重定向流量，并且在同步代理规则时具有更好的性能。此外，ipvs为负载均衡算法提供了更多选项，例如
- rr：轮询调度
- 1c：最小连接数
- dh：目标哈希
- sh：源哈希
- sed:最短期望延迟
- nq：不排队调度

**注意**: ipvs需要节点上的`ipvs内核模块`支持，如果未安装，则`kube-proxy`将回退到`iptables`代理模式

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggd18in55qj30l80eeqbs.jpg)

#### <span id="head17">3.3.2 查看ipvs代理规则</span>

```
ipvsadm -Ln
```

## <span id="head18">4. Headless Service</span>

`Headless Service`也是一种`Cluster IP`,只不过是一种特殊的Cluster IP

### <span id="head19">4.1 存在的意义</span>

- 有时不需要或不想要负载均衡，以及单独的Service IP。遇到这种情况，可以通过指定 `ClusterIP(spec.clusterIP)`的值为`None`来创建`Headless Service`。这类`Service`:
- 并不会分配 `Cluster IP`**
- `kube-proxy`不会处理它们
- 平台也不会为它们进行负载均衡和路由
- 主要的特点是通过无头服务的方式去解决hostname和portname的变化问题，也就是通过它去进行绑定

### <span id="head20">4.2 Headless Service资源清单</span>

```
apiVersion: v1 
kind: Service 
metadata:
  name: myapp-headless 
  namespace: default 
spec:
  selector:
    app: myapp 
  clusterIP: "None"
  ports:
  - port: 80 
    targetPort: 80
```
