### ISSUE TITLE
kubernetes系列(十一) - 存储之configMap

### ISSUE THREAD

**Issue by lzw5399** [lzw5399/blogs#14]
- [1. configMap简介](#head1)
	- [1.1 configMap的典型用法](#head2)
	- [1.2 configMap的表现形式](#head3)
- [2. configMap的创建方式](#head4)
	- [2.1 kubectl create命令行创建](#head5)
		- [2.1.1 从文件创建](#head6)
		- [2.1.2 从目录创建](#head7)
		- [2.1.3 使用字面值创建](#head8)
	- [2.2 使用yaml资源清单创建](#head9)
- [3. configMap的使用](#head10)
	- [3.1 使用configMap来替代环境变量](#head11)
	- [3.2 使用configMap设置容器启动命令的启动参数(需设置为环境变量)](#head12)
	- [3.3 通过数据卷插件volume使用ConfigMap](#head13)
		- [3.3.1 把整个configmap挂载到路径下](#head14)
		- [3.3.2 把configmap某个key的值，挂载到具体的文件](#head15)
- [4. configMap的热更新](#head16)
	- [4.1 热更新的局限](#head17)
	- [4.2 修改configmap](#head18)

## <span id="head1">1. configMap简介</span>

应用部署的一个最佳实践就是将应用所需的配置信息与程序分离，这样可以使应用更好地进行复用，通过不同的配置也可以实现更灵活的功能。
所以从`v1.2`开始，kubernetes提供了一种统一的应用配置管理方案-`configMap`

### <span id="head2">1.1 configMap的典型用法</span>

1. 生成为容器内的`环境变量`
2. 设置容器启动命令的启动参数(`需设置为环境变量`)
3. 以`volume`形式挂载为容器内部的文件或目录

### <span id="head3">1.2 configMap的表现形式</span>

`configMap`以一个或者多个`key:value`的形式保存，其中：
- 既可以是`loglevel=info`的形式
- 也可以表示一个完整的配置文件内容
   - 如：server.xml=<?xml...>...

#### <span id="head6">2.1.1 从文件创建</span>

1. 创建一个测试的配置文件test.json
```shell
echo "{ \"id\": \"emm\", \"name\": \"tom\"}" >> test.json
```

2. 从文件创建configmap
> key=文件名，value=文件内容
```shell
kubectl create cm map2 --from-file=test.json
```

3. 查看创建的configmap
```shell
kubectl describe cm map2
```

#### <span id="head7">2.1.2 从目录创建</span>

1. 准备文件夹和文件夹内容
```shell
mkdir cmtest && \
echo "{ \"id\": \"emm\", \"name\": \"tom\"}" >> cmtest/test.json &&\
echo "{ \"id\": \"emm\", \"name\": \"tom\"}" >> cmtest/test2.json
```

2. 从文件创建configmap
> key=文件夹下的每个文件名，value=文件内容
```shell
kubectl create cm map2 --from-file=cmtest/
```

#### <span id="head8">2.1.3 使用字面值创建</span>

使用文字值创建，利用`--from-literal`参数传递配置信息
- 该参数可以使用多次
```shell
kubectl create cm testname --from-literal=key1=value1 --from-literal=key2=value2
```

### <span id="head9">2.2 使用yaml资源清单创建</span>

下图分别演示了
- key对应一个value
- key对应一整个配置文件
```yaml
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: cm-name-1
  namespace: default 
data:
  key1: "hahah"
  key2: |
    {
      "property1": "value1",
      "property2": true
    }
```

### <span id="head11">3.1 使用configMap来替代环境变量</span>

共有两种使用方式：

1. 自己指定环境变量名字，使用configmap的值
2. 将整个configmap里面的`k/v`映射成环境变量
```yaml
apiVersion: v1 
kind: Pod 
metadata:
  name: dapi-test-pod 
spec:
  containers:
    - name: test-container 
      image: hub.coreqi.cn/library/myapp:v1 
      command: [ "/bin/sh", "-c", "env" ]
      # 自己指定环境变量名字，使用configmap的值
      env:
        - name: SPECIAL_LEVEL_KEY 
          valueFrom:
            configMapKeyRef:
              name: special-config 
              key: special.how
        - name: SPECIAL_TYPE_KEY 
          valueFrom:
            configMapKeyRef:
              name: special-config 
              key: special.type 
      
      # 将整个configmap里面的`k/v`映射成环境变量
　　  envFrom:
  　　  - configMapRef:
  　　    name: env-config 
  restartPolicy: Never
```

### <span id="head12">3.2 使用configMap设置容器启动命令的启动参数(需设置为环境变量)</span>

导入方式和环境变量一样的，这里主要体现的是一种思想，如下
- 能直接echo输出环境变量，**说明也能直接作为启动命令的参数使用**

```yaml
apiVersion: v1 
kind: Pod 
metadata:
  name: dapi-test-pod 
spec:
  containers: 
    - name: test-container 
      image: hub.coreqi.cn/library/myapp:v1 
      # 这里输出使用环境变量，说明也能当启动参数
      command: [ "/bin/sh","-c", "echo $(SPECIAL_LEVEL_KEY) $(SPECIAL_TYPE_KEY)" ] 
      env:
        - name: SPECIAL_LEVEL_KEY 
          valueFrom:
            configMapKeyRef: 
              name: special-config 
              key: special.how 
        - name: SPECIAL_TYPE_KEY 
          valueFrom:
            configMapKeyRef:
              name: special-config 
              key: special.type 
  restartPolicy: Never
```

#### <span id="head14">3.3.1 把整个configmap挂载到路径下</span>
- 此时这个路径下的
   - 文件名=key
   - 文件内容=value
```yaml
apiVersion: v1 
kind: Pod 
metadata:
  name: dapi-test-pod 
spec:
  containers:
    - name: test-container 
      image: hub.coreqi.cn/library/myapp:v1 
      command: [ "/bin/sh", "-c", "cat /etc/config/special.how" ]
      # 把config-volume挂载到下面的路径下
      volumeMounts:
      - name: config-volume 
        mountPath: /etc/config 
  # 导入“special-config”的configmap,并命名为config-volume
  volumes:
    - name: config-volume 
      configMap:
        name: special-config 
  restartPolicy: Never
```

#### <span id="head15">3.3.2 把configmap某个key的值，挂载到具体的文件</span>

```yaml
apiVersion: v1 
kind: Pod 
metadata:
  name: dapi-test-pod 
spec:
  containers:
    - name: test-container 
      image: hub.coreqi.cn/library/myapp:v1 
      command: [ "/bin/sh", "-c", "cat /etc/config/special.how" ]
      # 把config-volume下的key1的值。完整地赋值给appsettings.Production.json
      volumeMounts:
      - name: config-volume 
        mountPath: /app/appsettings.Production.json
        subPath: key1
  # 导入“special-config”的configmap,并命名为config-volume
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  restartPolicy: Never
```

### <span id="head17">4.1 热更新的局限</span>

1. 热更新只有对volume挂载文件的使用方式有效
2. **对该ConfigMap挂载的Env不会同步更新**

### <span id="head18">4.2 修改configmap</span>
```
kubectl edit configmap log-config
```

假如有资源挂载了这个configmap，等待大约十秒后就能热更新
