### ISSUE TITLE
kubernetes系列(十二) - 存储之Secret

### ISSUE THREAD

**Issue by lzw5399** [lzw5399/blogs#15]
- [1. Secret简介](#head1)
- [2. Secret类型](#head2)
- [3. Service Account](#head3)
- [4. Opaque](#head4)
	- [4.1 Opaque类型说明](#head5)
	- [4.2 Opaque创建方式](#head6)
		- [4.2.1 命令行创建](#head7)
		- [4.2.2 yaml资源清单创建](#head8)
	- [4.3 Opaque使用方式](#head9)
		- [4.3.1 将Secret挂载到Volume](#head10)
		- [4.3.2 将Secret导出到环境变量中](#head11)
- [5. Dockerconfigjson](#head12)
	- [5.1 创建docker-registry类型的secret](#head13)
	- [5.2 yaml中使用dockerconfigjson](#head14)
- [6. Tsl](#head15)
	- [6.1 创建tsl](#head16)
		- [6.1.1 直接指定文件创建](#head17)
		- [6.1.2 以yaml资源清单方式创建](#head18)
	- [6.2. 使用tsl secret](#head19)

## <span id="head1">1. Secret简介</span>

`Secret`解决了密码、token、密钥等敏感数据的配置问题，而不需要把这些敏感数据暴露到镜像或者`Pod Spec` 中。<br>
`Secret` 可以以以下两种方式使用:
- `volume`挂载
- 环境变量

## <span id="head2">2. Secret类型</span>

Secret有四种类型： 

注：一些教程说只有三种，经过笔者`kubectl create secret --help`查看，且回顾之前`ingress`七层代理的知识点，发现其他教程都漏了一种secret是`tsl`

1. `Service Account`
> 用来访问Kubernetes API，由Kubernetes 自动创建，并且会自动挂载到Pod的 /run/secrets/kubernetes.io/serviceaccount 目录中
2. `Opaque`
> `base64编码`格式的Secret，用来存储密码、密钥等.
3. `kubernetes.io/dockerconfigjson`
> 用来存储私有`docker registry`的认证信息
4. `kubernetes.io/tls`
> 用来存储`tsl`证书。一般是用来配合ingress实现`https`证书的配置,具体见`ingress`那章

## <span id="head3">3. Service Account</span>
- 用来访问`Kubernetes API Service`，由Kubernetes 自动创建，并且会自动挂载到Pod的 `/run/secrets/kubernetes.io/serviceaccount`目录中
- 即不是所有的pod都有权访问`api service`，不然会给`api service`造成很大的压力。
- `service account`不需要我们自己管理！

**示例**

如下，因为`kube-proxy`肯定会跟`api-servie`交互，所以查看他的`service account`
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggiq5nfb61j30kc08iab4.jpg)

----

### <span id="head5">4.1 Opaque类型说明</span>

Opaque类型的数据是一个 map类型，要求value是base64编码格式

**示例**

- 如下是base64编码和解码的：

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggir5kvtybj30c701uaa6.jpg)

#### <span id="head7">4.2.1 命令行创建</span>

1. **使用字面值创建**
- 通过命令行创建不用将value指定为`base64`，但是`yaml` 形式必须指定，不然创建会失败！
```shell
kubectl create secret generic my-sec --from-literal=key1=value1
```
如下，类型为`Opaque`:

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggir8zc9b2j30fn01vglp.jpg)

2. **使用文件或者文件夹创建**
> 跟configmap一样，都是使用`--from-file`
```shell
kubectl create secret generic my-sec --from-file=/一个文件夹或者一个文件
```

#### <span id="head8">4.2.2 yaml资源清单创建</span>

```yaml
apiVersion: v1 
kind: Secret 
metadata:
  name: mysecret 
type: Opaque 
data:
  password: MWYyZDF1MmU2N2Rm 
  username: YWRtaW4=
```

#### <span id="head10">4.3.1 将Secret挂载到Volume</span>

- 使用方式跟`configMap`差不多
```yaml
apiVersion: v1 
kind: Pod 
metadata:
  labels:
    name: seret-test 
  name: seret-test 
spec:
  # volume中导入secret
  volumes:
  - name: secrets 
    secret:
      secretName: mysecret 
  containers:
  - image: lzw5399/tocgenerator
    name: db 
    # mounts中使用volume中的secret
    volumeMounts:
    - name: secrets 
      mountPath: "/etc/secrets"
      readOnly: true
```

#### <span id="head11">4.3.2 将Secret导出到环境变量中</span>

- 使用方式跟`configMap`差不多
```yaml
apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: pod-deployment 
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        app: pod-deployment 
    spec:
      containers:
      - name: pod-1 
        image: lzw5399/tocgenerator
        ports:
        - containerPort: 80 
        # 将secret的值赋给环境变量
        env:
        - name: TEST_USER 
          valueFrom:
            secretKeyRef:
              name: mysecret 
              key: username 
        - name: TEST_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysecret 
              key: password
```

## <span id="head12">5. Dockerconfigjson</span>

用来存储私有`docker registry`的认证信息

### <span id="head13">5.1 创建docker-registry类型的secret</span>

```shell
kubectl create secret docker-registry myregistrykey --docker-server=hub.codepie.fun --docker-username=baoshu --docker-password=yourpwd --docker-email=baoshu@test.com
```

如下可以看到，创建出来的类型是`kubernetes.io/dockerconfigjson`

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggirywbxfbj30vx04174x.jpg)

### <span id="head14">5.2 yaml中使用dockerconfigjson</span>

```yaml
apiVersion: v1 
kind: Pod 
metadata:
  name: foo 
spec:
  containers:
    - name: foo 
      image: lzw5399/tocgenerator
  # 引用创建出来的dockerconfigjson
  imagePullSecrets:
    - name: myregistrykey
```

## <span id="head15">6. Tsl</span>

用来存储`tsl`证书。一般是用来配合ingress实现`https`证书的配置,可以参见`ingress`那篇

#### <span id="head17">6.1.1 直接指定文件创建</span>

```yaml
kubectl create secret tls toc-secret --key tls.key --cert tls.crt
```
![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggis48n1zpj30fd02u0sz.jpg)

#### <span id="head18">6.1.2 以yaml资源清单方式创建</span>

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mywebsite-secret
data:
  tls.crt: **************************
  tls.key: **************************

```

### <span id="head19">6.2. 使用tsl secret</span>

- 这里演示的是配置`ingress`，实现https域名访问
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tocgenerator-ingress
spec:
  tls:
    - hosts:
      - toc.codepie.fun
      # 使用tsl
      secretName: toc-secret
  rules:
    - host: toc.codepie.fun
      http:
        paths:
          - path: /
            backend:
              serviceName: tocgenerator-svc
              servicePort: 80
```
