### ISSUE TITLE
kubernetes系列(十三) - 存储之Volume

### ISSUE THREAD

**Issue by lzw5399** [lzw5399/blogs#16]
- [1. Volume简介](#head1)
	- [1.1 k8s的volume和docker的volume区别](#head2)
	- [1.2 kubernetes支持的volume类型](#head3)
- [2. 重点的volume类型](#head4)
	- [2.1 emptyDir](#head5)
		- [2.1.1 emptyDir简介](#head6)
		- [2.1.2 emptyDir常见用途](#head7)
		- [2.1.3 emptyDir的具体使用方式](#head8)
	- [2.2 hostPath](#head9)
		- [2.2.1 hostPath简介](#head10)
		- [2.2.2 hostPath用途](#head11)
		- [2.2.3 使用hostPath的注意事项](#head12)
		- [2.2.4 hostPath的具体定义方式](#head13)

## <span id="head1">1. Volume简介</span>

volume(存储卷)是pod中能够被多个容器访问的共享目录

### <span id="head2">1.1 k8s的volume和docker的volume区别</span>

1. Kubernete中的`volume`**被定义在pod上**，然后被**一个pod的多个容器**挂载到具体的文件目录下
2. Kubernetes中的`volume`和pod的生命周期相同，但与容器的生命周期不相关
   - 即容器重启volume不会丢失
   - 但是pod重启volume卷会丢失
      - *注意*：这里的volume卷丢失不代表volume对应的实际地址会丢失，而是`spec.volumes`的定义丢失。
3. kubernetes支持多种类型的volume

### <span id="head3">1.2 kubernetes支持的volume类型</span>

以下列举一些常见或者需要了解的volume类型：

1. emptyDir
   - 初始内容是空的的卷
2. hostPath
   - `hostpath`为在Pod上挂载宿主机上的文件或者目录
3. secret
   - 使用一个`secret volume`为pod提供加密信息
4. configMap
   - 使用一个`configMap`为pod提供配置信息
5. gitRepo
   - 通过挂载一个空目录，并且从`git`库`clone`一个`repository`以供`pod`使用
6. glusterfs
   - 使用开源的`glusterfs`网络文件系统的目录挂载到pod
7. awsElasticBlockStore
   - 对接`aws`云提供`volume`，了解即可
8. gcePersistentDisk
   - 对接谷歌云提供的`volume`，了解即可
9. azureDisk & azureFile
   - 对接微软`Azure`提供的`volume`，了解即可

#### <span id="head6">2.1.1 emptyDir简介</span>

当Pod 被分配给节点时，首先创建`emptyDir` 卷，并且只要该 Pod 在该节点上运行，该卷就会存在。正如卷的名字所述，它最初是空的。Pod中的容器可以读取和写入`emptyDir`卷中的相同文件
- 该卷可以挂载到**每个容器中的相同或不同路径上**
- 容器崩溃不会从节点中移除 pod,因此 `emptyDir`卷中的数据在容器崩溃时是安全的
- Pod被移除时,`emptyDir`中的数据将被永久删除。

#### <span id="head7">2.1.2 emptyDir常见用途</span>

- 临时空间。例如用于某些应用程序运行时所需的临时目录，且无需永久保存
- 长时间任务的中间过程checkPoint的临时保存目录
- 同一个pod下，一个容器需要从另一个容器中获取数据的目录（多容器共享目录）

#### <span id="head8">2.1.3 emptyDir的具体使用方式</span>

如下，此时`容器c1下的/path1`和`容器c2下的/path2`是对应的同一个目录。
```yaml
apiVersion: v1 
kind: Pod 
metadata:
  name: test-pd 
spec:
  containers:
  - image: lzw5399/tocgenerator
    name: c1
    # 把定义的cache-volume挂在到该容器c1下的/path1路径
    volumeMounts:
    - mountPath: /path1 
      name: cache-volume
  - image: lzw5399/codepie
    name: c2
    # 把定义的cache-volume挂在到该容器c2下的/path2路径
    volumeMounts:
    - mountPath: /path2
      name: cache-volume
  # 定义一个emptyDir的volume
  volumes:
  - name: cache-volume 
    emptyDir: {}
```

#### <span id="head10">2.2.1 hostPath简介</span>

`hostPath`卷将主机节点的文件系统中的**文件或目录**挂载到集群中

#### <span id="head11">2.2.2 hostPath用途</span>

1. 运行需要访问Docker 内部的容器；使用 `/var/lib/docker`的`hostPath`
2. 在容器中运行`cAdvisor`;使用`/dev/cgroups`的`hostPath`
3. 允许pod指定给定的`hostPath`是否应该在 pod运行之前存在，是否应该创建，以及它应该以什么形式存在

除了所需的path属性之外，用户还可以为hostPath卷制定type：

值 | 行为
---|---
&nbsp;| 空字符串 (`也是默认的行为`)用于向后兼容，这意味着在挂载 hostPath 卷之前不会执行任何检查。
DirectoryOrCreate|如果在给定的路径上没有任何东西存在，那么将根据需要在那里创建一个空目录，权限设置为0755,与Kubelet 具有相同的组和所有权。
Directory|给定的路径下必须存在目录
FileOrCreate|如果在给定的路径上没有任何东西存在，那么会根据需要创建一个空文件，权限设置为0644，与Kubelet具有相同的组和所有权。
File|给定的路径下必须存在文件
Socket|给定的路径下必须存在UNIX套接字
CharDevice|给定的路径下必须存在字符设备
BlockDevice|给定的路径下必须存在块设备

#### <span id="head12">2.2.3 使用hostPath的注意事项</span>

1. .由于每个节点上的文件都不同，具有相同配置(例如从`podTemplate`创建的)的pod**在不同节点上的行为可能会有所不同**
2. 当`Kubernetes`按照计划添加资源感知调度时，将无法考虑`hostPath`使用的资源
3. 在底层主机上创建的文件或目录只能由 root写入。您需要在特权容器中以 root身份运行进程，或修改主机上的文件权限以便写入`hostPath`卷

#### <span id="head13">2.2.4 hostPath的具体定义方式</span>

```yaml
apiVersion: v1 
kind: Pod 
metadata:
  name: test-pd 
spec:
  containers:
  - image: k8s.gcr.io/test-webserver 
    name: test-container 
    volumeMounts:
    - mountPath: /test-pd 
      name: test-volum
  # 定义一个hostPath类型的volume
  volumes:
  - name: test-volume 
    hostPath:
      # 路径挂载到宿主机的/data下
      path: /data 
      # (可选) 指定类型，见上面的表
      type: Directory
```
